### ISSUE TITLE
I found an error during install

### ISSUE THREAD

**Issue by Dafinity** [UBrainDev/btc-faucet#6]
PDOExeption error, could not connect to database. We are working on the issue, please come back later..
Une erreur est survenue lors de la connexion avec la base de données; nous travaillons sur le problème. Merci de revenir plus tard. PDOException: invalid data source name in /home/vol9_8/epizy.com/epiz_32592631/htdocs/src/config/pdo.php:12 Stack trace: #0 /home/vol9_8/epizy.com/epiz_32592631/htdocs/src/config/pdo.php(12): PDO->__construct('host=sql204.epi...', 'epiz_32592631', '2hgeX0yJXoSb3') #1 /home/vol9_8/epizy.com/epiz_32592631/htdocs/src/components/header.php(16): include_once('/home/vol9_8/ep...') #2 /home/vol9_8/epizy.com/epiz_32592631/htdocs/index.php(7): include_once('/home/vol9_8/ep...') #3 {main}

I've followed the install method through your tutorial, but it still doesn't work

**Comment by urbainn** [comment]
I think that the issue is linked with a misconfiguration with your database, could you double-check if all your credentials are correct and that your database is correctly working?

**Comment by Dafinity** [comment]
I have checked all the database names to connect to the server are correct. does that affect $dsn
